-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 02, 2021 at 09:59 AM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `oldcar`
--

-- --------------------------------------------------------

--
-- Table structure for table `cars`
--

CREATE TABLE `cars` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `active` tinyint(1) NOT NULL,
  `car_year` int(11) NOT NULL,
  `km` int(11) DEFAULT NULL,
  `short_description` varchar(80) CHARACTER SET utf8 DEFAULT NULL,
  `long_description` varchar(300) CHARACTER SET utf8 DEFAULT NULL,
  `car_price` int(11) NOT NULL,
  `model_id` int(11) DEFAULT NULL,
  `main_image` varchar(255) DEFAULT NULL,
  `second_image` varchar(255) DEFAULT NULL,
  `third_image` varchar(255) DEFAULT NULL,
  `fourth_image` varchar(255) DEFAULT NULL,
  `fifth_image` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `cars`
--

INSERT INTO `cars` (`id`, `user_id`, `active`, `car_year`, `km`, `short_description`, `long_description`, `car_price`, `model_id`, `main_image`, `second_image`, `third_image`, `fourth_image`, `fifth_image`) VALUES
(1, 1, 1, 1968, 10200, '1968 Aston Martin en muy buen estado y financiable si se prefiere!', 'Aston Martin DB2. Año 1968. Fabricado en Europa. Se trata de una de las versiones más apreciadas del Aston Martin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 35100, 1, 'AstonMartin/DB2/1-IMG1.jpg', 'AstonMartin/DB2/1-IMG2.jpg', 'AstonMartin/DB2/1-IMG3.jpg', 'AstonMartin/DB2/1-IMG4.jpg', 'AstonMartin/DB2/1-IMG5.jpg'),
(2, 2, 1, 1953, 5000, '1953 Aston Martin en muy buen estado y financiable si se prefiere!', 'Aston Martin DB2. Año 1953. Fabricado en Europa. Se trata de una de las versiones más apreciadas del Aston Martin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 42000, 1, 'AstonMartin/DB2/2-IMG1.jpg', 'AstonMartin/DB2/2-IMG2.jpg', 'AstonMartin/DB2/2-IMG3.jpg', 'AstonMartin/DB2/2-IMG4.jpg', 'AstonMartin/DB2/2-IMG5.jpg'),
(3, 11, 1, 1970, 3837, '1970 Aston Martin en muy buen estado y financiable si se prefiere!', 'Aston Martin DB6. Año 1970. Fabricado en Europa. Se trata de una de las versiones más apreciadas del Aston Martin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 51000, 2, 'AstonMartin/DB6/3-IMG1.jpg', 'AstonMartin/DB6/3-IMG2.jpg', 'AstonMartin/DB6/3-IMG3.jpg', 'AstonMartin/DB6/3-IMG4.jpg', 'AstonMartin/DB6/3-IMG5.png'),
(4, 4, 1, 1969, 8560, '1969 Aston Martin en muy buen estado y financiable si se prefiere!', 'Aston Martin DB6. Año 1969. Fabricado en Europa. Se trata de una de las versiones más apreciadas del Aston Martin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 69300, 2, 'AstonMartin/DB6/4-IMG1.jpg', 'AstonMartin/DB6/4-IMG2.jpg', 'AstonMartin/DB6/4-IMG3.jpg', 'AstonMartin/DB6/4-IMG4.jpg', 'AstonMartin/DB6/4-IMG5.jpg'),
(5, 5, 1, 1933, 128, '1933 Aston Martin en muy buen estado y financiable si se prefiere!', 'Aston Martin Lagonda. Año 1933. Fabricado en Europa. Se trata de una de las versiones más apreciadas del Aston Martin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 31250, 3, 'AstonMartin/Lagonda/5-IMG1.jpg', 'AstonMartin/Lagonda/5-IMG2.jpg', 'AstonMartin/Lagonda/5-IMG3.jpg', 'AstonMartin/Lagonda/5-IMG4.jpg', 'AstonMartin/Lagonda/5-IMG5.jpg'),
(11, 4, 1, 1961, 99999, '1961 Austin en muy buen estado y financiable si se prefiere!', 'Austin Frogeye Sprite. Año 1961. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Austin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 21360, 4, 'Austin/FrogeyeSprite/11-IMG1.jpg', 'Austin/FrogeyeSprite/11-IMG2.jpg', 'Austin/FrogeyeSprite/11-IMG3.jpg', 'Austin/FrogeyeSprite/11-IMG4.jpg', 'Austin/FrogeyeSprite/11-IMG5.jpg'),
(12, 7, 1, 1959, 6283, '1959 Austin en muy buen estado y financiable si se prefiere!', 'Austin Frogeye Sprite. Año 1959. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Austin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 39500, 4, 'Austin/FrogeyeSprite/12-IMG1.jpg', 'Austin/FrogeyeSprite/12-IMG2.jpg', 'Austin/FrogeyeSprite/12-IMG3.jpg', 'Austin/FrogeyeSprite/12-IMG4.jpg', 'Austin/FrogeyeSprite/12-IMG5.jpg'),
(13, 6, 1, 1967, 65, '1967 Austin en muy buen estado y financiable si se prefiere!', 'Austin Healey 3000 MK3. Año 1967. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Austin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 79650, 5, 'Austin/Healey3000MK3/13-IMG1.jpg', 'Austin/Healey3000MK3/13-IMG2.jpg', 'Austin/Healey3000MK3/13-IMG3.jpg', 'Austin/Healey3000MK3/13-IMG4.jpg', 'Austin/Healey3000MK3/13-IMG5.jpg'),
(14, 6, 1, 1965, 120000, '1965 Austin en muy buen estado y financiable si se prefiere!', 'Austin Healey 3000 MK3. Año 1965. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Austin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 63000, 5, 'Austin/Healey3000MK3/14-IMG1.jpg', 'Austin/Healey3000MK3/14-IMG2.jpg', 'Austin/Healey3000MK3/14-IMG3.jpg', 'Austin/Healey3000MK3/14-IMG4.jpg', 'Austin/Healey3000MK3/14-IMG5.jpg'),
(15, 1, 1, 1933, 1254, '1933 Austin en muy buen estado y financiable si se prefiere!', 'Austin Ten Cabrio. Año 1933. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Austin, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 15000, 6, 'Austin/TenCabrio/15-IMG1.jpg', '', 'Austin/TenCabrio/15-IMG3.jpg', 'Austin/TenCabrio/15-IMG4.jpg', 'Austin/TenCabrio/15-IMG5.jpg'),
(16, 5, 1, 1965, 91800, '1965 Bentley en muy buen estado y financiable si se prefiere!', 'Bentley Continental. Año 1965. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Bentley, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 120000, 7, 'Bentley/Continental/16-IMG1.jpg', 'Bentley/Continental/16-IMG2.jpg', 'Bentley/Continental/16-IMG3.jpg', 'Bentley/Continental/16-IMG4.jpg', 'Bentley/Continental/16-IMG5.jpg'),
(17, 2, 1, 1963, 45000, '1963 Bentley en muy buen estado y financiable si se prefiere!', 'Bentley Continental. Año 1963. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Bentley, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 67200, 7, 'Bentley/Continental/17-IMG1.jpg', 'Bentley/Continental/17-IMG2.jpg', 'Bentley/Continental/17-IMG3.jpg', 'Bentley/Continental/17-IMG4.jpg', 'Bentley/Continental/17-IMG5.jpg'),
(18, 6, 1, 1952, 179000, '1952 Bentley en muy buen estado y financiable si se prefiere!', 'Bentley Mark VI. Año 1952. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Bentley, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 63800, 8, 'Bentley/MarkVI/18-IMG1.jpg', 'Bentley/MarkVI/18-IMG2.jpg', 'Bentley/MarkVI/18-IMG3.jpg', 'Bentley/MarkVI/18-IMG4.jpg', 'Bentley/MarkVI/18-IMG5.jpg'),
(19, 7, 1, 1951, 1345, '1951 Bentley en muy buen estado y financiable si se prefiere!', 'Bentley S1. Año 1951. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Bentley, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 55000, 9, 'Bentley/S1/19-IMG1.jpg', 'Bentley/S1/19-IMG2.jpg', 'Bentley/S1/19-IMG3.jpg', 'Bentley/S1/19-IMG4.jpg', 'Bentley/S1/19-IMG5.jpg'),
(20, 2, 1, 1929, 151, '1929 Bentley en muy buen estado y financiable si se prefiere!', 'Bentley Special Old. Año 1929. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Bentley, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 77400, 10, 'Bentley/SpecialOld/20-IMG1.jpg', 'Bentley/SpecialOld/20-IMG2.jpg', 'Bentley/SpecialOld/20-IMG3.jpg', 'Bentley/SpecialOld/20-IMG4.jpg', 'Bentley/SpecialOld/20-IMG5.jpg'),
(21, 4, 1, 1938, 123000, '1938 Buick en muy buen estado y financiable si se prefiere!', 'Buick Model 24. Año 1938. Fabricado en USA. Se trata de una de las versiones más apreciadas de Buick, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 35000, 11, 'Buick/Model24/21-IMG1.jpg', 'Buick/Model24/21-IMG2.jpg', 'Buick/Model24/21-IMG3.jpg', 'Buick/Model24/21-IMG4.jpg', 'Buick/Model24/21-IMG5.jpg'),
(22, 7, 1, 1966, 893, '1966 Buick en muy buen estado y financiable si se prefiere!', 'Buick Riviera. Año 1966. Fabricado en USA. Se trata de una de las versiones más apreciadas de Buick, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 32000, 12, 'Buick/Riviera/22-IMG1.jpg', 'Buick/Riviera/22-IMG2.jpg', 'Buick/Riviera/22-IMG3.jpg', 'Buick/Riviera/22-IMG4.jpg', 'Buick/Riviera/22-IMG5.jpg'),
(23, 6, 1, 1972, 17000, '1972 Buick en muy buen estado y financiable si se prefiere!', 'Buick Riviera. Año 1972. Fabricado en USA. Se trata de una de las versiones más apreciadas de Buick, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 28950, 12, 'Buick/Riviera/23-IMG1.jpg', 'Buick/Riviera/23-IMG2.jpg', 'Buick/Riviera/23-IMG3.jpg', 'Buick/Riviera/23-IMG4.jpg', 'Buick/Riviera/23-IMG5.jpg'),
(24, 1, 1, 1948, 90561, '1948 Buick en muy buen estado y financiable si se prefiere!', 'Buick Roadmaster. Año 1948. Fabricado en USA. Se trata de una de las versiones más apreciadas de Buick, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 35800, 13, 'Buick/Roadmaster/24-IMG1.jpg', 'Buick/Roadmaster/24-IMG2.jpg', 'Buick/Roadmaster/24-IMG3.jpg', 'Buick/Roadmaster/24-IMG4.jpg', 'Buick/Roadmaster/24-IMG5.jpg'),
(25, 5, 1, 1949, 79890, '1949 Buick en muy buen estado y financiable si se prefiere!', 'Buick Super Sedan. Año 1949. Fabricado en USA. Se trata de una de las versiones más apreciadas de Buick, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 39500, 14, 'Buick/SuperSedan/25-IMG1.jpg', 'Buick/SuperSedan/25-IMG2.jpg', 'Buick/SuperSedan/25-IMG3.jpg', 'Buick/SuperSedan/25-IMG4.jpg', 'Buick/SuperSedan/25-IMG5.jpg'),
(26, 7, 1, 1968, 1788, '1968 Chevrolet en muy buen estado y financiable si se prefiere!', 'Chevrolet Camaro. Año 1968. Fabricado en USA. Se trata de una de las versiones más apreciadas de Chevrolet, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 39100, 15, 'Chevrolet/Camaro/26-IMG1.jpg', 'Chevrolet/Camaro/26-IMG2.jpg', 'Chevrolet/Camaro/26-IMG3.jpg', 'Chevrolet/Camaro/26-IMG4.jpg', 'Chevrolet/Camaro/26-IMG5.jpg'),
(27, 1, 1, 1979, 23000, '1979 Chevrolet en muy buen estado y financiable si se prefiere!', 'Chevrolet Camaro. Año 1979. Fabricado en USA. Se trata de una de las versiones más apreciadas de Chevrolet, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 28500, 15, 'Chevrolet/Camaro/27-IMG1.jpg', 'Chevrolet/Camaro/27-IMG2.jpg', 'Chevrolet/Camaro/27-IMG3.jpg', 'Chevrolet/Camaro/27-IMG4.jpg', 'Chevrolet/Camaro/27-IMG5.jpg'),
(28, 4, 1, 1964, 109000, '1964 Chevrolet en muy buen estado y financiable si se prefiere!', 'Chevrolet Corvette. Año 1964. Fabricado en USA. Se trata de una de las versiones más apreciadas de Chevrolet, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 45200, 16, 'Chevrolet/Corvette/28-IMG1.jpg', 'Chevrolet/Corvette/28-IMG2.jpg', 'Chevrolet/Corvette/28-IMG3.jpg', 'Chevrolet/Corvette/28-IMG4.jpg', 'Chevrolet/Corvette/28-IMG5.jpg'),
(29, 6, 1, 1968, 115800, '1968 Chevrolet en muy buen estado y financiable si se prefiere!', 'Chevrolet Corvette. Año 1968. Fabricado en USA. Se trata de una de las versiones más apreciadas de Chevrolet, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 32700, 16, 'Chevrolet/Corvette/29-IMG1.jpg', 'Chevrolet/Corvette/29-IMG2.jpg', 'Chevrolet/Corvette/29-IMG3.jpg', 'Chevrolet/Corvette/29-IMG4.jpg', 'Chevrolet/Corvette/29-IMG5.jpg'),
(30, 5, 1, 1928, 111, '1928 Chevrolet en muy buen estado y financiable si se prefiere!', 'Chevrolet Double Phantom. Año 1928. Fabricado en USA. Se trata de una de las versiones más apreciadas de Chevrolet, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 33200, 17, 'Chevrolet/DoublePhantom/30-IMG1.jpg', 'Chevrolet/DoublePhantom/30-IMG2.jpg', 'Chevrolet/DoublePhantom/30-IMG3.jpg', 'Chevrolet/DoublePhantom/30-IMG4.jpg', 'Chevrolet/DoublePhantom/30-IMG5.jpg'),
(31, 5, 1, 1953, 14000, '1953 Citroen en muy buen estado y financiable si se prefiere!', 'Citroen 2CV. Año 1953. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Citroen, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 13100, 18, 'Citroen/2CV/31-IMG1.jpg', 'Citroen/2CV/31-IMG2.jpg', 'Citroen/2CV/31-IMG3.jpg', 'Citroen/2CV/31-IMG4.jpg', 'Citroen/2CV/31-IMG5.jpg'),
(32, 1, 1, 1977, 58920, '1977 Citroen en muy buen estado y financiable si se prefiere!', 'Citroen 2CV. Año 1977. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Citroen, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 9630, 18, 'Citroen/2CV/32-IMG1.jpg', 'Citroen/2CV/32-IMG2.jpg', 'Citroen/2CV/32-IMG3.jpg', 'Citroen/2CV/32-IMG4.jpg', 'Citroen/2CV/32-IMG5.jpg'),
(33, 2, 1, 1969, 13, '1969 Citroen en muy buen estado y financiable si se prefiere!', 'Citroen DS Cabrio. Año 1969. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Citroen, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 105200, 19, 'Citroen/DsCabrio/33-IMG1.jpg', 'Citroen/DsCabrio/33-IMG2.jpg', 'Citroen/DsCabrio/33-IMG3.jpg', 'Citroen/DsCabrio/33-IMG4.jpg', 'Citroen/DsCabrio/33-IMG5.jpg'),
(34, 4, 1, 1949, 59542, '1949 Citroen en muy buen estado y financiable si se prefiere!', 'Citroen Traction. Año 1949. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Citroen, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 27200, 20, 'Citroen/Traction/34-IMG1.jpg', 'Citroen/Traction/34-IMG2.jpg', 'Citroen/Traction/34-IMG3.jpg', 'Citroen/Traction/34-IMG4.jpg', 'Citroen/Traction/34-IMG5.jpg'),
(35, 5, 1, 1954, 20980, '1954 Citroen en muy buen estado y financiable si se prefiere!', 'Citroen Traction. Año 1954. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Citroen, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 11000, 20, 'Citroen/Traction/35-IMG1.jpg', 'Citroen/Traction/35-IMG2.jpg', 'Citroen/Traction/35-IMG3.jpg', 'Citroen/Traction/35-IMG4.jpg', 'Citroen/Traction/35-IMG5.jpg'),
(36, 6, 1, 1972, 36200, '1972 De Tomaso en muy buen estado y financiable si se prefiere!', 'De Tomaso Pantera. Año 1972. Fabricado en Europa. Se trata de una de las versiones más apreciadas De Tomaso, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 115095, 21, 'DeTomaso/Pantera/36-IMG1.jpg', 'DeTomaso/Pantera/36-IMG2.jpg', 'DeTomaso/Pantera/36-IMG3.jpg', 'DeTomaso/Pantera/36-IMG4.jpg', 'DeTomaso/Pantera/36-IMG5.jpg'),
(37, 2, 1, 1971, 105200, '1971 De Tomaso en muy buen estado y financiable si se prefiere!', 'De Tomaso Pantera. Año 1971. Fabricado en Europa. Se trata de una de las versiones más apreciadas De Tomaso, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 69800, 21, 'DeTomaso/Pantera/37-IMG1.jpg', 'DeTomaso/Pantera/37-IMG2.jpg', 'DeTomaso/Pantera/37-IMG3.jpg', 'DeTomaso/Pantera/37-IMG4.jpg', 'DeTomaso/Pantera/37-IMG5.jpg'),
(38, 7, 1, 1985, 71132, '1985 De Tomaso en muy buen estado y financiable si se prefiere!', 'De Tomaso Deauville. Año 1985. Fabricado en Europa. Se trata de una de las versiones más apreciadas De Tomaso, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 38600, 22, 'DeTomaso/Deauville/38-IMG1.jpg', 'DeTomaso/Deauville/38-IMG2.jpg', 'DeTomaso/Deauville/38-IMG3.jpg', 'DeTomaso/Deauville/38-IMG4.jpg', 'DeTomaso/Deauville/38-IMG5.jpg'),
(39, 8, 1, 1949, 50000, '1949 Fiat en muy buen estado y financiable si se prefiere!', 'Fiat 500. Año 1949. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Fiat, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 13200, 23, 'Fiat/500/39-IMG1.jpg', 'Fiat/500/39-IMG2.jpg', 'Fiat/500/39-IMG3.jpg', 'Fiat/500/39-IMG4.jpg', 'Fiat/500/39-IMG5.jpg'),
(40, 9, 1, 1927, 52000, '1927 Fiat en muy buen estado y financiable si se prefiere!', 'Fiat 500. Año 1927. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Fiat, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 42100, 23, 'Fiat/500/40-IMG1.jpg', 'Fiat/500/40-IMG2.jpg', 'Fiat/500/40-IMG3.jpg', 'Fiat/500/40-IMG4.jpg', 'Fiat/500/40-IMG5.jpg'),
(41, 11, 1, 1960, 42000, '1960 Fiat en muy buen estado y financiable si se prefiere!', 'Fiat Balilla. Año 1960. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Fiat, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 5500, 24, 'Fiat/Balilla/41-IMG1.jpg', 'Fiat/Balilla/41-IMG2.jpg', 'Fiat/Balilla/41-IMG3.jpg', 'Fiat/Balilla/41-IMG4.jpg', 'Fiat/Balilla/41-IMG5.jpg'),
(42, 7, 1, 1926, 2000, '1926 Fiat en muy buen estado y financiable si se prefiere!', 'Fiat Spider. Año 1926. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Fiat, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 30000, 25, 'Fiat/Spider/42-IMG1.jpg', 'Fiat/Spider/42-IMG2.jpg', 'Fiat/Spider/42-IMG3.jpg', 'Fiat/Spider/42-IMG4.jpg', 'Fiat/Spider/42-IMG5.jpg'),
(43, 10, 1, 1927, 600, '1927 Fiat en muy buen estado y financiable si se prefiere!', 'Fiat Torpedo. Año 1927. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Fiat, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 89500, 26, 'Fiat/Torpedo/43-IMG1.jpg', 'Fiat/Torpedo/43-IMG2.jpg', 'Fiat/Torpedo/43-IMG3.jpg', 'Fiat/Torpedo/43-IMG4.jpg', 'Fiat/Torpedo/43-IMG5.jpg'),
(44, 10, 1, 1953, 99000, '1953 Ford en muy buen estado y financiable si se prefiere!', 'Ford F 100. Año 1953. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Ford, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 31800, 27, 'Ford/F100/44-IMG1.jpg', 'Ford/F100/44-IMG2.jpg', 'Ford/F100/44-IMG3.jpg', 'Ford/F100/44-IMG4.jpg', 'Ford/F100/44-IMG5.jpg'),
(45, 8, 1, 1928, 16000, '1928 Ford en muy buen estado y financiable si se prefiere!', 'Ford T. Año 1928. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Ford, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 14900, 28, 'Ford/T/45-IMG1.jpg', 'Ford/T/45-IMG2.jpg', 'Ford/T/45-IMG3.jpg', 'Ford/T/45-IMG4.jpg', 'Ford/T/45-IMG5.jpg'),
(46, 9, 1, 1927, 18900, '1927 Ford en muy buen estado y financiable si se prefiere!', 'Ford T. Año 1927. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Ford, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 21100, 28, 'Ford/T/46-IMG1.jpg', 'Ford/T/46-IMG2.jpg', 'Ford/T/46-IMG3.jpg', 'Ford/T/46-IMG4.jpg', 'Ford/T/46-IMG5.jpg'),
(47, 11, 1, 1926, 99000, '1926 Ford en muy buen estado y financiable si se prefiere!', 'Ford Roadster. Año 1926. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Ford, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 28000, 29, 'Ford/Roadster/47-IMG1.jpg', 'Ford/Roadster/47-IMG2.jpg', 'Ford/Roadster/47-IMG3.jpg', 'Ford/Roadster/47-IMG4.jpg', 'Ford/Roadster/47-IMG5.jpg'),
(48, 11, 1, 1955, 105000, '1955 Ford en muy buen estado y financiable si se prefiere!', 'Ford Thunderbird. Año 1955. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Ford, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 48000, 30, 'Ford/Thunderbird/48-IMG1.jpg', 'Ford/Thunderbird/48-IMG2.jpg', 'Ford/Thunderbird/48-IMG3.jpg', 'Ford/Thunderbird/48-IMG4.jpg', 'Ford/Thunderbird/48-IMG5.jpg'),
(49, 8, 1, 1956, 78000, '1956 Ford en muy buen estado y financiable si se prefiere!', 'Ford Thunderbird. Año 1956. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Ford, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 31400, 30, 'Ford/Thunderbird/49-IMG1.jpg', 'Ford/Thunderbird/49-IMG2.jpg', 'Ford/Thunderbird/49-IMG3.jpg', 'Ford/Thunderbird/49-IMG4.jpg', 'Ford/Thunderbird/49-IMG5.jpg'),
(50, 10, 1, 1962, 12532, '1962 Jaguar en muy buen estado y financiable si se prefiere!', 'Jaguar E-Type. Año 1962. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Jaguar, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 180000, 31, 'Jaguar/E-Type/50-IMG1.jpg', 'Jaguar/E-Type/50-IMG2.jpg', 'Jaguar/E-Type/50-IMG3.jpg', 'Jaguar/E-Type/50-IMG4.jpg', 'Jaguar/E-Type/50-IMG5.jpg'),
(52, 2, 1, 1960, 81200, '1960 Jaguar en muy buen estado y financiable si se prefiere!', 'Jaguar MKII. Año 1960. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Jaguar, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 43850, 32, 'Jaguar/MKII/52-IMG1.jpg', 'Jaguar/MKII/52-IMG2.jpg', 'Jaguar/MKII/52-IMG3.jpg', 'Jaguar/MKII/52-IMG4.jpg', 'Jaguar/MKII/52-IMG5.jpg'),
(53, 7, 1, 1961, 18000, '1961 Jaguar en muy buen estado y financiable si se prefiere!', 'Jaguar MKII. Año 1961. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Jaguar, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 50000, 32, 'Jaguar/MKII/53-IMG1.jpg', 'Jaguar/MKII/53-IMG2.jpg', 'Jaguar/MKII/53-IMG3.jpg', 'Jaguar/MKII/53-IMG4.jpg', 'Jaguar/MKII/53-IMG5.jpg'),
(54, 6, 1, 1950, 24750, '1950 Jaguar en muy buen estado y financiable si se prefiere!', 'Jaguar XK 120. Año 1950. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Jaguar, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 120000, 33, 'Jaguar/XK120/54-IMG1.jpg', 'Jaguar/XK120/54-IMG2.jpg', 'Jaguar/XK120/54-IMG3.jpg', 'Jaguar/XK120/54-IMG4.jpg', 'Jaguar/XK120/54-IMG5.jpg'),
(63, 2, 1, 1922, 49500, '1922 Almicar en muy buen estado y financiable si se prefiere!', 'Almicar del año 1922. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Almicar, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 99800, 34, 'OldTimer/ALMICAR/63-IMG1.jpg', 'OldTimer/ALMICAR/63-IMG2.jpg', 'OldTimer/ALMICAR/63-IMG3.jpg', 'OldTimer/ALMICAR/63-IMG4.jpg', 'OldTimer/ALMICAR/63-IMG5.jpg'),
(64, 11, 1, 1919, 5900, '1919 Chevrolet en muy buen estado y financiable si se prefiere!', 'Chevrolet del año 1919. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Chevrolet, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 19900, 35, 'OldTimer/CHEVROLET/64-IMG1.jpg', 'OldTimer/CHEVROLET/64-IMG2.jpg', 'OldTimer/CHEVROLET/64-IMG3.jpg', 'OldTimer/CHEVROLET/64-IMG4.jpg', 'OldTimer/CHEVROLET/64-IMG5.jpg'),
(65, 5, 1, 1921, 1, '1921 Overige en muy buen estado y financiable si se prefiere!', 'Overige del año 1921. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Overige, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 42450, 36, 'OldTimer/OVERIGE/65-IMG1.jpg', 'OldTimer/OVERIGE/65-IMG2.jpg', 'OldTimer/OVERIGE/65-IMG3.jpg', 'OldTimer/OVERIGE/65-IMG4.jpg', 'OldTimer/OVERIGE/65-IMG5.jpg'),
(66, 1, 1, 1922, 18, '1922 Tourer en muy buen estado y financiable si se prefiere!', 'Tourier del año 1922. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Tourer, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 10200, 37, 'OldTimer/TOURER/66-IMG1.jpg', 'OldTimer/TOURER/66-IMG2.jpg', 'OldTimer/TOURER/66-IMG3.jpg', 'OldTimer/TOURER/66-IMG4.jpg', 'OldTimer/TOURER/66-IMG5.jpg'),
(67, 9, 1, 1927, 54000, '1927 Pontiac en muy buen estado y financiable si se prefiere!', 'Pontiac 6-27 Coupe. Año 1927. Fabricado en USA. Se trata de una de las versiones más apreciadas de Pontiac, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 18950, 38, 'Pontiac/6-27Coupe/67-IMG1.jpg', 'Pontiac/6-27Coupe/67-IMG2.jpg', 'Pontiac/6-27Coupe/67-IMG3.jpg', 'Pontiac/6-27Coupe/67-IMG4.jpg', 'Pontiac/6-27Coupe/67-IMG5.jpg'),
(68, 6, 1, 1954, 91800, '1954 Pontiac en muy buen estado y financiable si se prefiere!', 'Pontiac Catalina. Año 1954. Fabricado en USA. Se trata de una de las versiones más apreciadas de Pontiac, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 29700, 39, 'Pontiac/Catalina/68-IMG1.jpg', 'Pontiac/Catalina/68-IMG2.jpg', 'Pontiac/Catalina/68-IMG3.jpg', 'Pontiac/Catalina/68-IMG4.jpg', 'Pontiac/Catalina/68-IMG5.jpg'),
(69, 1, 1, 1971, 160145, '1971 Pontiac en muy buen estado y financiable si se prefiere!', 'Pontiac Firebird. Año 1971. Fabricado en USA. Se trata de una de las versiones más apreciadas de Pontiac, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 52200, 40, 'Pontiac/Firebird/69-IMG1.jpg', 'Pontiac/Firebird/69-IMG2.jpg', 'Pontiac/Firebird/69-IMG3.jpg', 'Pontiac/Firebird/69-IMG4.jpg', 'Pontiac/Firebird/69-IMG5.jpg'),
(70, 8, 1, 1965, 160930, '1965 Pontiac en muy buen estado y financiable si se prefiere!', 'Pontiac GTO. Año 1965. Fabricado en USA. Se trata de una de las versiones más apreciadas de Pontiac, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 62300, 41, 'Pontiac/GTO/70-IMG1.jpg', 'Pontiac/GTO/70-IMG2.jpg', 'Pontiac/GTO/70-IMG3.jpg', 'Pontiac/GTO/70-IMG4.jpg', 'Pontiac/GTO/70-IMG5.jpg'),
(71, 5, 1, 1969, 21650, '1969 Pontiac en muy buen estado y financiable si se prefiere!', 'Pontiac GTO. Año 1969. Fabricado en USA. Se trata de una de las versiones más apreciadas de Pontiac, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 39950, 41, 'Pontiac/GTO/71-IMG1.jpg', 'Pontiac/GTO/71-IMG2.jpg', 'Pontiac/GTO/71-IMG3.jpg', 'Pontiac/GTO/71-IMG4.jpg', 'Pontiac/GTO/71-IMG5.jpg'),
(72, 11, 1, 1933, 111102, '1933 Rolls-Royce en muy buen estado y financiable si se prefiere!', 'Rolls-Royce Freestone. Año 1933. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Rolls-Royce, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 158000, 42, 'RollsRoyce/Freestone/72-IMG1.jpg', 'RollsRoyce/Freestone/72-IMG2.jpg', 'RollsRoyce/Freestone/72-IMG3.jpg', 'RollsRoyce/Freestone/72-IMG4.jpg', 'RollsRoyce/Freestone/72-IMG5.jpg'),
(73, 11, 1, 1929, 10236, '1929 Rolls-Royce en muy buen estado y financiable si se prefiere!', 'Rolls-Royce Phantom II. Año 1929. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Rolls-Royce, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 280000, 43, 'RollsRoyce/PhantomII/73-IMG1.jpg', 'RollsRoyce/PhantomII/73-IMG2.jpg', 'RollsRoyce/PhantomII/73-IMG3.jpg', 'RollsRoyce/PhantomII/73-IMG4.jpg', 'RollsRoyce/PhantomII/73-IMG5.jpg'),
(74, 7, 1, 1934, 88888, '1934 Rolls-Royce en muy buen estado y financiable si se prefiere!', 'Rolls-Royce Phantom II. Año 1934. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Rolls-Royce, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 200000, 43, 'RollsRoyce/PhantomII/74-IMG1.jpg', 'RollsRoyce/PhantomII/74-IMG2.jpg', 'RollsRoyce/PhantomII/74-IMG3.jpg', 'RollsRoyce/PhantomII/74-IMG4.jpg', 'RollsRoyce/PhantomII/74-IMG5.jpg'),
(75, 11, 1, 1952, 35210, '1952 Rolls-Royce en muy buen estado y financiable si se prefiere!', 'Rolls-Royce Silver. Año 1952. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Rolls-Royce, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 102000, 44, 'RollsRoyce/Silver/75-IMG1.jpg', 'RollsRoyce/Silver/75-IMG2.jpg', 'RollsRoyce/Silver/75-IMG3.jpg', 'RollsRoyce/Silver/75-IMG4.jpg', 'RollsRoyce/Silver/75-IMG5.jpg'),
(76, 10, 1, 1954, 99320, '1954 Rolls-Royce en muy buen estado y financiable si se prefiere!', 'Rolls Royce Silver. Año 1954. Fabricado en Europa. Se trata de una de las versiones más apreciadas de Rolls-Royce, esta unidad en concreto se encuentra en muy buen estado de conservación. Combustible gasolina. Un clásico con merecida reputación de fiabilidad y estética entrañable.', 79000, 44, 'RollsRoyce/Silver/76-IMG1.jpg', 'RollsRoyce/Silver/76-IMG2.jpg', 'RollsRoyce/Silver/76-IMG3.jpg', 'RollsRoyce/Silver/76-IMG4.jpg', 'RollsRoyce/Silver/76-IMG5.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cars`
--
ALTER TABLE `cars`
  ADD PRIMARY KEY (`id`),
  ADD KEY `cars_brands` (`model_id`),
  ADD KEY `cars_users` (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cars`
--
ALTER TABLE `cars`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=226;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `cars`
--
ALTER TABLE `cars`
  ADD CONSTRAINT `FK_95C71D147975B7E7` FOREIGN KEY (`model_id`) REFERENCES `models` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `cars_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
